import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          {children}
          <Toaster />
        </ToastProvider>
        <footer className="mt-12">
          <p className="text-xs text-muted-foreground"> {new Date().getFullYear()} Zemen Pharma. All rights reserved.</p>
          <nav className="flex items-center gap-4 text-xs text-muted-foreground">
            <a className="hover:text-foreground" href="/terms">Terms of service</a>
            <a className="hover:text-foreground" href="/privacy">Privacy policy</a>
          </nav>
        </footer>
      </body>
    </html>
  );
}
