"""new head

Revision ID: f77b96e35eb5
Revises: 6095eff5dfa8
Create Date: 2025-11-02 14:11:02.146003

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "f77b96e35eb5"
down_revision = '6095eff5dfa8'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pharmacies_name', table_name='pharmacies')
    op.drop_index('ix_pharmacies_tenant_id', table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index('ix_notification_preferences_type', table_name='notification_preferences')
    op.drop_index('ix_notification_preferences_user_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_tenant_activity_logs_action', table_name='tenant_activity_logs')
    op.drop_index('ix_tenant_activity_logs_actor_user_id', table_name='tenant_activity_logs')
    op.drop_index('ix_tenant_activity_logs_tenant_id', table_name='tenant_activity_logs')
    op.drop_table('tenant_activity_logs')
    op.drop_index('ix_branches_name', table_name='branches')
    op.drop_index('ix_branches_pharmacy_id', table_name='branches')
    op.drop_index('ix_branches_tenant_id', table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_medicines_category', table_name='medicines')
    op.drop_index('ix_medicines_name', table_name='medicines')
    op.drop_index('ix_medicines_sku', table_name='medicines')
    op.drop_index('ix_medicines_tenant_id', table_name='medicines')
    op.drop_table('medicines')
    op.drop_index('ix_chat_threads_owner_user_id', table_name='chat_threads')
    op.drop_index('ix_chat_threads_tenant_id', table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index('ix_affiliate_profiles_code', table_name='affiliate_profiles')
    op.drop_index('ix_affiliate_profiles_user_id', table_name='affiliate_profiles')
    op.drop_table('affiliate_profiles')
    op.drop_index('ix_chat_messages_role', table_name='chat_messages')
    op.drop_index('ix_chat_messages_tenant_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_thread_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_kyc_applications_applicant_user_id', table_name='kyc_applications')
    op.drop_index('ix_kyc_applications_status', table_name='kyc_applications')
    op.drop_index('ix_kyc_applications_tenant_id', table_name='kyc_applications')
    op.drop_table('kyc_applications')
    op.drop_index('ix_notifications_tenant_id', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_commission_payouts_affiliate_user_id', table_name='commission_payouts')
    op.drop_index('ix_commission_payouts_month', table_name='commission_payouts')
    op.drop_index('ix_commission_payouts_status', table_name='commission_payouts')
    op.drop_index('ix_commission_payouts_tenant_id', table_name='commission_payouts')
    op.drop_table('commission_payouts')
    op.drop_index('ix_integration_staging_records_tenant_id', table_name='integration_staging_records')
    op.drop_table('integration_staging_records')
    op.drop_index('ix_verification_codes_code', table_name='verification_codes')
    op.drop_index('ix_verification_codes_email', table_name='verification_codes')
    op.drop_index('ix_verification_codes_purpose', table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index('ix_sale_items_medicine_id', table_name='sale_items')
    op.drop_index('ix_sale_items_sale_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_affiliate_referrals_affiliate_user_id', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_code', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_referred_tenant_id', table_name='affiliate_referrals')
    op.drop_table('affiliate_referrals')
    op.drop_index('ix_customers_tenant_id', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_integration_connections_tenant_id', table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_integration_sync_jobs_tenant_id', table_name='integration_sync_jobs')
    op.drop_table('integration_sync_jobs')
    op.drop_index('ix_integration_providers_key', table_name='integration_providers')
    op.drop_table('integration_providers')
    op.drop_index('ix_user_tenants_tenant_id', table_name='user_tenants')
    op.drop_index('ix_user_tenants_user_id', table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index('ix_users_assigned_branch_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sales_branch', table_name='sales')
    op.drop_index('ix_sales_cashier_user_id', table_name='sales')
    op.drop_index('ix_sales_customer_id', table_name='sales')
    op.drop_index('ix_sales_tenant_id', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_affiliate_links_active', table_name='affiliate_links')
    op.drop_index('ix_affiliate_links_affiliate_user_id', table_name='affiliate_links')
    op.drop_index('ix_affiliate_links_token', table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_index('ix_payment_submissions_code', table_name='payment_submissions')
    op.drop_index('ix_payment_submissions_status', table_name='payment_submissions')
    op.drop_index('ix_payment_submissions_submitted_by_user_id', table_name='payment_submissions')
    op.drop_index('ix_payment_submissions_tenant_id', table_name='payment_submissions')
    op.drop_table('payment_submissions')
    op.drop_index('ix_inventory_items_branch', table_name='inventory_items')
    op.drop_index('ix_inventory_items_medicine_id', table_name='inventory_items')
    op.drop_index('ix_inventory_items_tenant_id', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('ai_usage')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_auth_sessions_tenant_id', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_user_id', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('_alembic_tmp_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('assigned_branch_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_branch_id'], ['branches.id'], name='fk_users_assigned_branch_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('last_seen_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_auth_sessions_user_id', 'auth_sessions', ['user_id'], unique=False)
    op.create_index('ix_auth_sessions_tenant_id', 'auth_sessions', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('actor_user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=128), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('thread_id', sa.INTEGER(), nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=64), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('reorder_level', sa.INTEGER(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('lot_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('pack_size', sa.INTEGER(), nullable=False),
    sa.Column('purchase_price', sa.FLOAT(), nullable=True),
    sa.Column('sell_price', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_items_tenant_id', 'inventory_items', ['tenant_id'], unique=False)
    op.create_index('ix_inventory_items_medicine_id', 'inventory_items', ['medicine_id'], unique=False)
    op.create_index('ix_inventory_items_branch', 'inventory_items', ['branch'], unique=False)
    op.create_table('payment_submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('submitted_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_submissions_tenant_id', 'payment_submissions', ['tenant_id'], unique=False)
    op.create_index('ix_payment_submissions_submitted_by_user_id', 'payment_submissions', ['submitted_by_user_id'], unique=False)
    op.create_index('ix_payment_submissions_status', 'payment_submissions', ['status'], unique=False)
    op.create_index('ix_payment_submissions_code', 'payment_submissions', ['code'], unique=False)
    op.create_table('affiliate_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('affiliate_user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliate_links_token', 'affiliate_links', ['token'], unique=1)
    op.create_index('ix_affiliate_links_affiliate_user_id', 'affiliate_links', ['affiliate_user_id'], unique=False)
    op.create_index('ix_affiliate_links_active', 'affiliate_links', ['active'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('cashier_user_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=64), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('discount_amount', sa.FLOAT(), nullable=False),
    sa.Column('tax_amount', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_tenant_id', 'sales', ['tenant_id'], unique=False)
    op.create_index('ix_sales_customer_id', 'sales', ['customer_id'], unique=False)
    op.create_index('ix_sales_cashier_user_id', 'sales', ['cashier_user_id'], unique=False)
    op.create_index('ix_sales_branch', 'sales', ['branch'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('assigned_branch_id', sa.INTEGER(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_index('ix_users_assigned_branch_id', 'users', ['assigned_branch_id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('role_override', sa.VARCHAR(length=32), nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tenants_user_id', 'user_tenants', ['user_id'], unique=False)
    op.create_index('ix_user_tenants_tenant_id', 'user_tenants', ['tenant_id'], unique=False)
    op.create_table('integration_providers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_providers_key', 'integration_providers', ['key'], unique=1)
    op.create_table('integration_sync_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), nullable=False),
    sa.Column('resource', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_sync_jobs_tenant_id', 'integration_sync_jobs', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('next_due_date', sa.DATE(), nullable=False),
    sa.Column('blocked', sa.BOOLEAN(), nullable=False),
    sa.Column('notices_sent', sa.INTEGER(), nullable=False),
    sa.Column('last_notice_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=1)
    op.create_table('integration_connections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('provider_id', sa.INTEGER(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=True),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('token_expiry', sa.DATETIME(), nullable=True),
    sa.Column('scopes', sa.TEXT(), nullable=True),
    sa.Column('extra_metadata', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_connections_tenant_id', 'integration_connections', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=32), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('meds_regimen', sa.TEXT(), nullable=True),
    sa.Column('refill_frequency_days', sa.INTEGER(), nullable=True),
    sa.Column('next_refill_date', sa.DATE(), nullable=True),
    sa.Column('last_refill_date', sa.DATE(), nullable=True),
    sa.Column('loyalty_tier', sa.VARCHAR(length=64), nullable=True),
    sa.Column('engagement_notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_tenant_id', 'customers', ['tenant_id'], unique=False)
    op.create_table('affiliate_referrals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('affiliate_user_id', sa.INTEGER(), nullable=False),
    sa.Column('referred_tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('activated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliate_referrals_referred_tenant_id', 'affiliate_referrals', ['referred_tenant_id'], unique=False)
    op.create_index('ix_affiliate_referrals_code', 'affiliate_referrals', ['code'], unique=False)
    op.create_index('ix_affiliate_referrals_affiliate_user_id', 'affiliate_referrals', ['affiliate_user_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sale_id', sa.INTEGER(), nullable=False),
    sa.Column('medicine_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('line_total', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_sale_id', 'sale_items', ['sale_id'], unique=False)
    op.create_index('ix_sale_items_medicine_id', 'sale_items', ['medicine_id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=32), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('consumed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_codes_purpose', 'verification_codes', ['purpose'], unique=False)
    op.create_index('ix_verification_codes_email', 'verification_codes', ['email'], unique=False)
    op.create_index('ix_verification_codes_code', 'verification_codes', ['code'], unique=False)
    op.create_table('integration_staging_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('resource', sa.VARCHAR(length=50), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_staging_records_tenant_id', 'integration_staging_records', ['tenant_id'], unique=False)
    op.create_table('commission_payouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('affiliate_user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), nullable=False),
    sa.Column('percent', sa.FLOAT(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commission_payouts_tenant_id', 'commission_payouts', ['tenant_id'], unique=False)
    op.create_index('ix_commission_payouts_status', 'commission_payouts', ['status'], unique=False)
    op.create_index('ix_commission_payouts_month', 'commission_payouts', ['month'], unique=False)
    op.create_index('ix_commission_payouts_affiliate_user_id', 'commission_payouts', ['affiliate_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_tenant_id', 'notifications', ['tenant_id'], unique=False)
    op.create_table('kyc_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('applicant_user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('pharmacy_license_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('pharmacy_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pharmacy_address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('owner_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('owner_phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('documents_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('license_document_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('license_document_mime', sa.VARCHAR(length=64), nullable=True),
    sa.Column('license_document_data', sa.BLOB(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('decided_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_applications_tenant_id', 'kyc_applications', ['tenant_id'], unique=False)
    op.create_index('ix_kyc_applications_status', 'kyc_applications', ['status'], unique=False)
    op.create_index('ix_kyc_applications_applicant_user_id', 'kyc_applications', ['applicant_user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thread_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_thread_id', 'chat_messages', ['thread_id'], unique=False)
    op.create_index('ix_chat_messages_tenant_id', 'chat_messages', ['tenant_id'], unique=False)
    op.create_index('ix_chat_messages_role', 'chat_messages', ['role'], unique=False)
    op.create_table('affiliate_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bank_account_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('iban', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliate_profiles_user_id', 'affiliate_profiles', ['user_id'], unique=False)
    op.create_index('ix_affiliate_profiles_code', 'affiliate_profiles', ['code'], unique=1)
    op.create_table('chat_threads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('owner_user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_threads_tenant_id', 'chat_threads', ['tenant_id'], unique=False)
    op.create_index('ix_chat_threads_owner_user_id', 'chat_threads', ['owner_user_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=64), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medicines_tenant_id', 'medicines', ['tenant_id'], unique=False)
    op.create_index('ix_medicines_sku', 'medicines', ['sku'], unique=False)
    op.create_index('ix_medicines_name', 'medicines', ['name'], unique=False)
    op.create_index('ix_medicines_category', 'medicines', ['category'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('pharmacy_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_branches_tenant_id', 'branches', ['tenant_id'], unique=False)
    op.create_index('ix_branches_pharmacy_id', 'branches', ['pharmacy_id'], unique=False)
    op.create_index('ix_branches_name', 'branches', ['name'], unique=False)
    op.create_table('tenant_activity_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('actor_user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=128), nullable=False),
    sa.Column('message', sa.VARCHAR(length=512), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_activity_logs_tenant_id', 'tenant_activity_logs', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_activity_logs_actor_user_id', 'tenant_activity_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_tenant_activity_logs_action', 'tenant_activity_logs', ['action'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.create_index('ix_notification_preferences_type', 'notification_preferences', ['type'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pharmacies_tenant_id', 'pharmacies', ['tenant_id'], unique=1)
    op.create_index('ix_pharmacies_name', 'pharmacies', ['name'], unique=False)
    # ### end Alembic commands ###
